using System;
using KuyumHesap.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KuyumHesap.Persistence.Configurations
{
    public class AccountConfiguration : IEntityTypeConfiguration<Account>
    {
        public void Configure(EntityTypeBuilder<Account> builder)
        {
            builder.HasOne(a => a.AccountType)
                   .WithMany(at => at.Accounts)
                   .HasForeignKey(a => a.AccountTypeId)
                   .OnDelete(DeleteBehavior.NoAction);

            // Accounts Seed Data
            builder.HasData(
                new Account { Id = 1, AccountName = "TEST", AccountTypeId = 14, CustomerType = "Bireysel", MobilePhone = "05353348460", Email = "", NationalIdNumber = "", TaxOffice = "", TaxNumber = "", Country = "Türkiye", City = "", District = "", Neighborhood = "", FullAddress = "", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-04-18T09:11:16.7791766"), IsDeleted = false, CreatedByUserId = 0 },
                new Account { Id = 4, AccountName = "AHLATÇI", AccountTypeId = 3, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9621624"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 5, AccountName = "AHMET KAVALCI", AccountTypeId = 2, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622095"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 6, AccountName = "AKBANK HAVALE", AccountTypeId = 5, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622133"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 7, AccountName = "AKBANK POS", AccountTypeId = 6, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622158"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 8, AccountName = "ANA SERMAYE", AccountTypeId = 1, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622181"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 9, AccountName = "DOVİZ ALIŞ-SATIŞ K/Z", AccountTypeId = 10, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622211"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 10, AccountName = "ELMAS TAŞ GRUBU STOKLARI", AccountTypeId = 14, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622239"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 11, AccountName = "GİDER AİDAT", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622265"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 12, AccountName = "GİDER ALARM TESİSAT BAKIM", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622288"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 13, AccountName = "GİDER AMBALAJ", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622316"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 14, AccountName = "GİDER BAĞIŞ YARDIM", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622338"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 15, AccountName = "GİDER BANKA KOMİSYONLARI", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622364"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 16, AccountName = "GİDER BANKA MASRAFLARI", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622389"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 17, AccountName = "GİDER DİĞER", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622410"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 18, AccountName = "GİDER ELEKTRİK FATURASI", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622432"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 19, AccountName = "GİDER İKRAM ve YEMEK", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622649"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 20, AccountName = "GİDER İNTERNET", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622674"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 21, AccountName = "GİDER KARGO", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622700"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 22, AccountName = "GİDER KİRA", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622722"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 23, AccountName = "GİDER MAĞAZA TAMİR BAKIM", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622745"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 24, AccountName = "GİDER MUHASEBE", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9622772"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 25, AccountName = "GİDER PERSONEL MAAŞ", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632428"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 26, AccountName = "GİDER PERSONEL PRİMLERİ", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632486"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 27, AccountName = "GİDER PERSONEL SİGORTA", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632520"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 28, AccountName = "GİDER PERSONEL YEMEK", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632552"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 29, AccountName = "GİDER REKLAM", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632583"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 30, AccountName = "GİDER ULAŞIM", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632612"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 31, AccountName = "GİDER VERGİ", AccountTypeId = 8, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632638"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 32, AccountName = "HAKİ MUSTAFA ALKAN", AccountTypeId = 2, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632665"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 33, AccountName = "HURDA ALIŞ-SATIŞ K/Z", AccountTypeId = 10, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632695"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 34, AccountName = "HURDA GRUBU STOKLARI", AccountTypeId = 14, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632756"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 35, AccountName = "İSKONTO CARİDEN", AccountTypeId = 9, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632788"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 36, AccountName = "KASA2", AccountTypeId = 7, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632897"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 37, AccountName = "MADEN GRUBU STOKLARI", AccountTypeId = 14, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632925"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 38, AccountName = "MAHMUT KAVALCI", AccountTypeId = 2, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632958"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 39, AccountName = "MAMUL GRUBU STOKLARI", AccountTypeId = 14, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9632987"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 40, AccountName = "MAZLUM KUYUMCULUK", AccountTypeId = 3, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9633014"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 41, AccountName = "PIRLANTA TAŞ GRUBU STOKLARI", AccountTypeId = 14, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9633078"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 42, AccountName = "RAŞİT DUMAN", AccountTypeId = 13, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = true, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9633111"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 43, AccountName = "RENKLİ TAŞ GRUBU STOKLARI", AccountTypeId = 14, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9633144"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 44, AccountName = "ÜRÜN SATIŞ-İADE K/Z", AccountTypeId = 10, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9633204"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 45, AccountName = "ZERAY KUYUMCULUK", AccountTypeId = 3, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:38:30.9633254"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 46, AccountName = "AHLATÇI", AccountTypeId = 3, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-30T00:41:39.7716036"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 47, AccountName = "KASA 1", AccountTypeId = 7, CustomerType = "Sistem", Country = "Türkiye", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-03-03T00:00:00.0000000"), IsDeleted = false, CreatedByUserId = 1 },
                new Account { Id = 48, AccountName = "PEŞİN MÜŞTERİ", AccountTypeId = 2, CustomerType = "Bireysel", MobilePhone = "05353348460", Email = "", NationalIdNumber = "", TaxOffice = "", TaxNumber = "", Country = "Türkiye", City = "", District = "", Neighborhood = "", FullAddress = "", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-04-13T15:23:21.4587413"), IsDeleted = false, CreatedByUserId = 0 },
                new Account { Id = 49, AccountName = "KUYUMCU ORHAN", AccountTypeId = 3, CustomerType = "Bireysel", MobilePhone = "", Email = "", NationalIdNumber = "", TaxOffice = "", TaxNumber = "", Country = "Türkiye", City = "", District = "", Neighborhood = "", FullAddress = "", IsActive = true, IsCashier = false, CreatedDate = DateTime.Parse("2026-04-19T12:34:54.2034818"), IsDeleted = false, CreatedByUserId = 0 }
            );
        }
    }
}
