using KuyumHesap.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KuyumHesap.Persistence.Configurations
{
    public class MovementTypeConfiguration : IEntityTypeConfiguration<MovementType>
    {
        public void Configure(EntityTypeBuilder<MovementType> builder)
        {
            var data = new MovementType[]
            {
                new MovementType
                {
                    Id = 1,
                    TransactionCode = "NG",
                    TransactionName = "NAKİT GİRİŞ",
                    GC = 'G',
                    SC = 'C',
                    IsActive = true,
                    Description = "NAKİT GİRİŞ İŞLEMLERİ İÇİN KULLANILIR",
                    AutoGeneratedTransactionTypeId = 2,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
                new MovementType
                {
                    Id = 2,
                    TransactionCode = "NC",
                    TransactionName = "NAKİT ÇIKIŞ",
                    GC = 'C',
                    SC = 'G',
                    IsActive = true,
                    Description = "NAKİT ÇIKIŞ İŞLEMLERİ İÇİN KULLANILIR",
                    AutoGeneratedTransactionTypeId = 1,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
                new MovementType
                {
                    Id = 3,
                    TransactionCode = "UG",
                    TransactionName = "ÜRÜN GİRİŞ",
                    GC = 'G',
                    SC = 'C',
                    IsActive = true,
                    Description = "ÜRÜN GİRİŞ İŞLEMLERİ İÇİN KULLANILIR",
                    AutoGeneratedTransactionTypeId = 4,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
                new MovementType
                {
                    Id = 4,
                    TransactionCode = "UC",
                    TransactionName = "ÜRÜN ÇIKIŞ",
                    GC = 'C',
                    SC = 'C',
                    IsActive = true,
                    Description = "ÜRÜN ÇIKIŞ İŞLEMLERİ İÇİN KULLANILIR",
                    AutoGeneratedTransactionTypeId = 3,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
                new MovementType
                {
                    Id = 5,
                    TransactionCode = "ALC",
                    TransactionName = "ISKONTO ALACAKLANDIR",
                    GC = 'G',
                    SC = 'C',
                    IsActive = true,
                    Description = "HESABIN ALACAĞINA İSKONTO YAZMAK İÇİN",
                    AutoGeneratedTransactionTypeId = 6,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
                new MovementType
                {
                    Id = 6,
                    TransactionCode = "BRC",
                    TransactionName = "ISKONTO BORCLANDIR",
                    GC = 'C',
                    SC = 'C',
                    IsActive = true,
                    Description = "HESABIN BORCUNA İSKONTO YAZMAK İÇİN",
                    AutoGeneratedTransactionTypeId = 5,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
                new MovementType
                {
                    Id = 7,
                    TransactionCode = "VRG",
                    TransactionName = "VİRMAN GİRİŞ",
                    GC = 'G',
                    SC = 'C',
                    IsActive = true,
                    Description = "VİRMAN(HAVALE) GİRİŞ İŞLEMLERİ İÇİN KULLANILIR",
                    AutoGeneratedTransactionTypeId = 8,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
                new MovementType
                {
                    Id = 8,
                    TransactionCode = "VRC",
                    TransactionName = "VİRMAN ÇIKIŞ",
                    GC = 'C',
                    SC = 'C',
                    IsActive = true,
                    Description = "VİRMAN(HAVALE) ÇIKIŞ İŞLEMLERİ İÇİN KULLANILIR",
                    AutoGeneratedTransactionTypeId = 7,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
                new MovementType
                {
                    Id = 9,
                    TransactionCode = "CVG",
                    TransactionName = "ÇEVİRME GİRİŞ",
                    GC = 'G',
                    SC = 'C',
                    IsActive = true,
                    Description = "ÇEVİRME GİRİŞ İŞLEMLERİ İÇİN KULLANILIR",
                    AutoGeneratedTransactionTypeId = 10,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
                new MovementType
                {
                    Id = 10,
                    TransactionCode = "CVC",
                    TransactionName = "ÇEVİRME ÇIKIŞ",
                    GC = 'C',
                    SC = 'C',
                    IsActive = true,
                    Description = "ÇEVİRME ÇIKIŞ İŞLEMLERİ İÇİN KULLANILIR",
                    AutoGeneratedTransactionTypeId = 9,
                    CreatedByUserId = 1,
                              CreatedDate=new DateTime(2026,04,01)
                },
            };
            builder.HasData(data);


        }
    }
}
