// <auto-generated />
using System;
using KuyumHesap.Persistence.Common.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuyumHesap.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCashier")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BalanceOrder")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubBalanceCalculated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountTypeName = "SERMAYELER",
                            BalanceOrder = 100,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5078),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = true
                        },
                        new
                        {
                            Id = 2,
                            AccountTypeName = "MÜŞTERİLER",
                            BalanceOrder = 1,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5082),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        },
                        new
                        {
                            Id = 3,
                            AccountTypeName = "TOPTANCILAR",
                            BalanceOrder = 2,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5083),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        },
                        new
                        {
                            Id = 4,
                            AccountTypeName = "ATÖLYELER",
                            BalanceOrder = 3,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5084),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        },
                        new
                        {
                            Id = 5,
                            AccountTypeName = "BANKALAR",
                            BalanceOrder = 4,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5085),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        },
                        new
                        {
                            Id = 6,
                            AccountTypeName = "POSLAR",
                            BalanceOrder = 5,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5086),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        },
                        new
                        {
                            Id = 7,
                            AccountTypeName = "KASALAR",
                            BalanceOrder = 6,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5087),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        },
                        new
                        {
                            Id = 8,
                            AccountTypeName = "GİDER/GELİR",
                            BalanceOrder = 7,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5089),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = true
                        },
                        new
                        {
                            Id = 9,
                            AccountTypeName = "İSKONTOLAR",
                            BalanceOrder = 8,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5090),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = true
                        },
                        new
                        {
                            Id = 10,
                            AccountTypeName = "KAR/ZARAR",
                            BalanceOrder = 9,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5091),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = true
                        },
                        new
                        {
                            Id = 11,
                            AccountTypeName = "DEMİRBAŞLAR",
                            BalanceOrder = 10,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5092),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        },
                        new
                        {
                            Id = 12,
                            AccountTypeName = "ÖZELHESAPLAR",
                            BalanceOrder = 11,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5093),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        },
                        new
                        {
                            Id = 13,
                            AccountTypeName = "PERSONEL",
                            BalanceOrder = 12,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5094),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        },
                        new
                        {
                            Id = 14,
                            AccountTypeName = "STOKLAR",
                            BalanceOrder = 13,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(5095),
                            IsActive = true,
                            IsDeleted = false,
                            IsSubBalanceCalculated = false
                        });
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.BarcodeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarcodeHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsBold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeHeaderId");

                    b.ToTable("BarcodeDetails");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.BarcodeHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRfid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StartHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BarcodeHeaders");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBaseCurrency")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNationalCurrency")
                        .HasColumnType("bit");

                    b.Property<string>("MetaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SellRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("ExchangeRateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PreviousCloseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SellRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.ExchangeRateTicker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SellRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRateTickers");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.MovementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutoGeneratedTransactionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GC")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SC")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MovementTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoGeneratedTransactionTypeId = 2,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6500),
                            Description = "NAKİT GİRİŞ İŞLEMLERİ İÇİN KULLANILIR",
                            GC = "G",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "C",
                            TransactionCode = "NG",
                            TransactionName = "NAKİT GİRİŞ"
                        },
                        new
                        {
                            Id = 2,
                            AutoGeneratedTransactionTypeId = 1,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6508),
                            Description = "NAKİT ÇIKIŞ İŞLEMLERİ İÇİN KULLANILIR",
                            GC = "C",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "G",
                            TransactionCode = "NC",
                            TransactionName = "NAKİT ÇIKIŞ"
                        },
                        new
                        {
                            Id = 3,
                            AutoGeneratedTransactionTypeId = 4,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6510),
                            Description = "ÜRÜN GİRİŞ İŞLEMLERİ İÇİN KULLANILIR",
                            GC = "G",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "C",
                            TransactionCode = "UG",
                            TransactionName = "ÜRÜN GİRİŞ"
                        },
                        new
                        {
                            Id = 4,
                            AutoGeneratedTransactionTypeId = 3,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6512),
                            Description = "ÜRÜN ÇIKIŞ İŞLEMLERİ İÇİN KULLANILIR",
                            GC = "C",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "C",
                            TransactionCode = "UC",
                            TransactionName = "ÜRÜN ÇIKIŞ"
                        },
                        new
                        {
                            Id = 5,
                            AutoGeneratedTransactionTypeId = 6,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6513),
                            Description = "HESABIN ALACAĞINA İSKONTO YAZMAK İÇİN",
                            GC = "G",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "C",
                            TransactionCode = "ALC",
                            TransactionName = "ISKONTO ALACAKLANDIR"
                        },
                        new
                        {
                            Id = 6,
                            AutoGeneratedTransactionTypeId = 5,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6515),
                            Description = "HESABIN BORCUNA İSKONTO YAZMAK İÇİN",
                            GC = "C",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "C",
                            TransactionCode = "BRC",
                            TransactionName = "ISKONTO BORCLANDIR"
                        },
                        new
                        {
                            Id = 7,
                            AutoGeneratedTransactionTypeId = 8,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6516),
                            Description = "VİRMAN(HAVALE) GİRİŞ İŞLEMLERİ İÇİN KULLANILIR",
                            GC = "G",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "C",
                            TransactionCode = "VRG",
                            TransactionName = "VİRMAN GİRİŞ"
                        },
                        new
                        {
                            Id = 8,
                            AutoGeneratedTransactionTypeId = 7,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6518),
                            Description = "VİRMAN(HAVALE) ÇIKIŞ İŞLEMLERİ İÇİN KULLANILIR",
                            GC = "C",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "C",
                            TransactionCode = "VRC",
                            TransactionName = "VİRMAN ÇIKIŞ"
                        },
                        new
                        {
                            Id = 9,
                            AutoGeneratedTransactionTypeId = 10,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6520),
                            Description = "ÇEVİRME GİRİŞ İŞLEMLERİ İÇİN KULLANILIR",
                            GC = "G",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "C",
                            TransactionCode = "CVG",
                            TransactionName = "ÇEVİRME GİRİŞ"
                        },
                        new
                        {
                            Id = 10,
                            AutoGeneratedTransactionTypeId = 9,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(6521),
                            Description = "ÇEVİRME ÇIKIŞ İŞLEMLERİ İÇİN KULLANILIR",
                            GC = "C",
                            IsActive = true,
                            IsDeleted = false,
                            SC = "C",
                            TransactionCode = "CVC",
                            TransactionName = "ÇEVİRME ÇIKIŞ"
                        });
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Movements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseCurrencyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CounterCurrencyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CounterCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CounterExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CounterTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ForeignCurrencyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ForeignCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ForeignExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLaborIncluded")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReconciled")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LaborQuantity")
                        .HasColumnType("int");

                    b.Property<string>("LaborUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MillRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NetProductValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProfitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalLaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("StockId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(7432),
                            IsDeleted = false,
                            ProductTypeName = "YÜZÜK"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(7435),
                            IsDeleted = false,
                            ProductTypeName = "KÜPE"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(7436),
                            IsDeleted = false,
                            ProductTypeName = "ALYANS"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(7437),
                            IsDeleted = false,
                            ProductTypeName = "BİLEKLİK"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(7437),
                            IsDeleted = false,
                            ProductTypeName = "KELEPÇE"
                        });
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCustomerReceipt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OpenBalanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(8298),
                            IsDeleted = false,
                            Name = "Admin",
                            Type = "System"
                        },
                        new
                        {
                            Id = 2,
                            Code = "USER",
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(8302),
                            IsDeleted = false,
                            Name = "User",
                            Type = "System"
                        });
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LaborUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("MillRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockGroupId")
                        .HasColumnType("int");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StockUnitId")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockGroupId");

                    b.HasIndex("StockTypeId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.StockGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StockGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StockGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(9114),
                            IsDeleted = false,
                            StockGroupName = "MAMUL GRUBU"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(9116),
                            IsDeleted = false,
                            StockGroupName = "MADEN GRUBU"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(9117),
                            IsDeleted = false,
                            StockGroupName = "HURDA GRUBU"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(9118),
                            IsDeleted = false,
                            StockGroupName = "PIRLANTA TAŞ GRUBU"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(9120),
                            IsDeleted = false,
                            StockGroupName = "ELMAS TAŞ GRUBU"
                        },
                        new
                        {
                            Id = 6,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(9121),
                            IsDeleted = false,
                            StockGroupName = "RENKLİ TAŞ GRUBU"
                        });
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.StockType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockGroupId")
                        .HasColumnType("int");

                    b.Property<string>("StockTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("StockGroupId");

                    b.ToTable("StockTypes");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("BagliHesapID")
                        .HasColumnType("int");

                    b.Property<string>("BarkodYaziciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FisYaziciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("VarsayilanYaziciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 148, DateTimeKind.Local).AddTicks(9899),
                            Email = "mahmut.kavalci@gmail.com",
                            FirstName = "Mahmut",
                            IsDeleted = false,
                            LastName = "Kavalcı",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "+905353348460",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedByUserId = 0,
                            CreatedDate = new DateTime(2026, 1, 1, 16, 50, 41, 149, DateTimeKind.Local).AddTicks(313),
                            Email = "samt51.m@icloud.com",
                            FirstName = "Samet",
                            IsDeleted = false,
                            LastName = "Bağlan",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "+905363956979",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.VwModels.EkstreSatirViewModel", b =>
                {
                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BakiyeBirimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BakiyeEtkiMiktari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EskiBakiye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FisID")
                        .HasColumnType("int");

                    b.Property<bool>("GirisMi")
                        .HasColumnType("bit");

                    b.Property<int>("HareketID")
                        .HasColumnType("int");

                    b.Property<int>("HareketTipID")
                        .HasColumnType("int");

                    b.Property<int>("HesapID")
                        .HasColumnType("int");

                    b.Property<int?>("IscAdet")
                        .HasColumnType("int");

                    b.Property<string>("IscBrm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IscDahil")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Iscilik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KarsiHareketID")
                        .HasColumnType("int");

                    b.Property<string>("KarsilikBirim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("KarsilikKuru")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KarsilikMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Kur")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Milyem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Mutabakat")
                        .HasColumnType("bit");

                    b.Property<decimal>("SonBakiye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StokAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StokID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ToplamIscilik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tutar_BPBR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UrunHasDegeri")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("vw_HesapEkstresi", (string)null);
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Account", b =>
                {
                    b.HasOne("KuyumHesap.Domain.Entities.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.BarcodeDetail", b =>
                {
                    b.HasOne("KuyumHesap.Domain.Entities.BarcodeHeader", "BarcodeHeader")
                        .WithMany("BarcodeDetails")
                        .HasForeignKey("BarcodeHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarcodeHeader");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.ExchangeRate", b =>
                {
                    b.HasOne("KuyumHesap.Domain.Entities.Currency", "Currency")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Movements", b =>
                {
                    b.HasOne("KuyumHesap.Domain.Entities.Account", "Account")
                        .WithMany("Movements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuyumHesap.Domain.Entities.Currency", null)
                        .WithMany("Movements")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("KuyumHesap.Domain.Entities.Receipt", "Receipt")
                        .WithMany("Movements")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuyumHesap.Domain.Entities.Stock", "Stock")
                        .WithMany("Movements")
                        .HasForeignKey("StockId");

                    b.HasOne("KuyumHesap.Domain.Entities.MovementType", "TransactionType")
                        .WithMany("Movements")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Receipt");

                    b.Navigation("Stock");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Receipt", b =>
                {
                    b.HasOne("KuyumHesap.Domain.Entities.Account", "Account")
                        .WithMany("Receipts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Stock", b =>
                {
                    b.HasOne("KuyumHesap.Domain.Entities.StockGroup", "StockGroup")
                        .WithMany("Stocks")
                        .HasForeignKey("StockGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuyumHesap.Domain.Entities.StockType", "StockType")
                        .WithMany("Stocks")
                        .HasForeignKey("StockTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockGroup");

                    b.Navigation("StockType");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.StockType", b =>
                {
                    b.HasOne("KuyumHesap.Domain.Entities.Currency", "Currency")
                        .WithMany("StockTypes")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuyumHesap.Domain.Entities.StockGroup", "StockGroup")
                        .WithMany("StockTypes")
                        .HasForeignKey("StockGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("StockGroup");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("KuyumHesap.Domain.Entities.Users", "AssignedByUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuyumHesap.Domain.Entities.Users", "AssignedToUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Users", b =>
                {
                    b.HasOne("KuyumHesap.Domain.Entities.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Account", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.BarcodeHeader", b =>
                {
                    b.Navigation("BarcodeDetails");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Currency", b =>
                {
                    b.Navigation("ExchangeRates");

                    b.Navigation("Movements");

                    b.Navigation("StockTypes");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.MovementType", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Receipt", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Stock", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.StockGroup", b =>
                {
                    b.Navigation("StockTypes");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.StockType", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("KuyumHesap.Domain.Entities.Users", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
