using KuyumHesap.Domain.Command;

namespace KuyumHesap.Domain.Entities
{
    /// <summary>
    /// iŞlem Hareket Tipleri Tablosu
    /// </summary>
    public class MovementType : BaseEntity
    {
        /// <summary>
        /// Hareket tipi kodu (örn: SATIS, ALIS, TAHSILAT vb.)
        /// </summary>
        public string TransactionCode { get; set; } = null!;

        /// <summary>
        /// Hareket tipi adı
        /// </summary>
        public string TransactionName { get; set; } = null!;

        /// <summary>
        /// Borç / Alacak yönü (G = Giriş, C = Çıkış)
        /// </summary>
        public char DebitCreditFlag { get; set; }

        /// <summary>
        /// Stok giriş / çıkış yönü (S = Stok Giriş, C = Stok Çıkış)
        /// </summary>
        public char StockInOutFlag { get; set; }

        /// <summary>
        /// Hareket tipinin aktiflik durumu
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// Hareket tipi ile ilgili açıklama
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Otomatik oluşturulan karşı hareket tipi kimliği
        /// </summary>
        public int? AutoGeneratedTransactionTypeId { get; set; }
        public List<Movements> Movements { get; set; }

        public MovementType(List<Movements> movements)
        {
            Movements = movements;
        }
    }
}
