<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\AccountFeature\Exceptions\" />
    <Folder Include="Features\AuthFeature\Queries\" />
    <Folder Include="Features\BarcodeDetailFeature\Queries\" />
    <Folder Include="Features\ReceiptFeature\Dtos\" />
    <Folder Include="Features\ReportFeature\Commands\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Features\AccountFeature\Command\Create\CreateAccountCommandHandler.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KuyumHesap.Domain\KuyumHesap.Domain.csproj" />
  </ItemGroup>

</Project>
